### ISSUE TITLE
Implement a Remote Configuration Facility

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-AndroidApplication#11]
There is need for the capability to update local configuration in the Android Application remotely, some common scenarios might be:
1. to point users to a new endpoint URL for failover by updating RADAR-CNS/RADAR-AndroidApplication/blob/master/server.xml (or the SQL lite db where this could be stored)
2. to update arbitrary configuration on how data is collected (e.g. change sampling freq put for GPS) 

Some criteria:
- ideally this functionality would be bundled with the RADAR platform (I guess at its simplest perhaps simply by periodically polling a URL for updates)
- there are off the shelf solutions that might work better e.g. 
https://firebase.google.com/docs/remote-config/, however, this creates dependency on commercial products, although Firebase allows 100 concurrent connections for free, there is a strong preference in RADAR to keep the core platform open source 
- support cross platform, Android/iOS
- HTTPS
- preference for pub-sub

Please add your suggestions, I know this is probably a common issue encountered for Android/iOS.

cc/ @fnobilia @MaximMoinat @blootsvoets @nivemaham @herkulano @kerzmaximilian

**Comment by MaximMoinat** [comment]
Good point. Will check how this can be integrated.

**Comment by MaximMoinat** [comment]
@afolarin Today, we have started on this feature in the feature-firebase branch. It is work in progress, but the basics already work.

One note: it is now 'connected' to my own Google Account. If we wish to use Firebase, we should create a new google account which we can all access.

**Comment by blootsvoets** [comment]
This is done.
