### ISSUE TITLE
When the device goes offline, stop the KafkaDataSubmitter

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/RADAR-AndroidApplication#4]
Right now the KafkaDataSubmitter only checks for HTTP connectivity, and retries every so often if it fails. If we listen for internet connectivity on the device, we can stop the data submitter proactively.

Bonus: check for WiFi/Ethernet vs 3G/4G, and decrease the amount of messages in the latter case.

**Comment by afolarin** [comment]
> Right now the KafkaDataSubmitter only checks for HTTP connectivity, and retries every so often if it fails.

Is it worth having an incremental backoff, rather than a periodic check?

**Comment by blootsvoets** [comment]
Yes that might be better. Right now it's a randomised period between 5 and 15 minutes so at least different clients don't fall in sync.

Listening for local connectivity events is far more effective though if the connectivity problem is local.

**Comment by afolarin** [comment]
> Listening for local connectivity events is far more effective though if the connectivity problem is local.
agreed.

**Comment by blootsvoets** [comment]
This fix also adds a exponential back-off, as suggested.
