### ISSUE TITLE
Kafka sender timeout

### ISSUE THREAD

**Issue by MaximMoinat** [RADAR-CNS/RADAR-AndroidApplication#7]
Kafka sender times out (`SocketTimeoutException`) when there is a delay in sending data to the server, e.g. when internet is disconnected. The sender keeps trying to upload the same data, but fails every time. Thus, the sender is stuck in this loop.

**Comment by afolarin** [comment]
Unrelated to #4 ?

**Comment by MaximMoinat** [comment]
Related, but not completely similar, this also happens when there is an internet connection. 

The simple fix was to increase the write timeout of the HTTP connection and decrease the number of records send in one request.
